spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/botprofile_editor?serverTimezone=UTC
    username: root
    password: 818714
#mybatis-plus:
#  mapper-locations: classpath*:/mapper/*Mapper.xml